### ISSUE TITLE
USM chapter design

### ISSUE THREAD

**Issue by imvucic** [KhronosGroup/SYCL_Reference#78]
Here we can discuss about potential USM chapter section design.

**Current status in ref guide :** 

Unified shared memory (USM)
- [* ] malloc Functions
- [ *]   sycl::usm_allocator
- [ *]   sycl::usm::alloc

![Screenshot from 2023-10-16 10-19-39](https://github.com/KhronosGroup/SYCL_Reference/assets/145783173/13441e42-9189-46be-84d5-12c4fbbe8695)

**SYCL 2020 rev8 status :**

4.8. Unified shared memory (USM)

- [ ] 4.8.1. Unified addressing
- [ ] 4.8.2. Kinds of unified shared memory
- [ ] 4.8.3. USM allocations
        - [ ] 4.8.3.1. C++ allocator interface
        - [ ] 4.8.3.2. Device allocation functions
        - [ ] 4.8.3.3. Host allocation functions
        - [ ] 4.8.3.4. Shared allocation functions
        - [ ] 4.8.3.5. Parameterized allocation functions
        - [ ] 4.8.3.6. Memory deallocation functions
- [ ] 4.8.4. Unified shared memory pointer queries

![Screenshot from 2023-10-16 10-19-58](https://github.com/KhronosGroup/SYCL_Reference/assets/145783173/81a4f620-0c12-4025-bbf7-5eff81541026)

**Potential list of section and sub-section after comparation :** 

Unified shared memory (USM)

- [* ] Basic concept
      - Describe USM like in 4.8 beginning with example  
- [* ] Kinds of unified shared memory
     - Following 4.8.2 content with mention of  Unified addressing on the beggining
- [ *] USM allocations
     - The biggest chapter which following 4.8.3 sub structures : 
              4.8.3.1. C++ allocator interface
              4.8.3.2. Device allocation functions
              4.8.3.3. Host allocation functions
              4.8.3.4. Shared allocation functions
              4.8.3.5. Parameterized allocation functions
              4.8.3.6. Memory deallocation functions

- [* ] Pointer queries
       - Describe 4.8.4. Unified shared memory pointer queries

Could you please review and provide your opinion and recommendation for future section view?

**Comment by gmlueck** [comment]
I think this looks good.  The section "Kinds of unified shared memory" doesn't need to contain a deep description.  Instead, it can just introduce the fact that there are three types of USM (device, host, and shared), and it can have a pointer to specification section 4.8.2 for more details.

If you want, the reference guide could include this information about the three USM types in the "Basic concept" section, rather than having a separate "Kinds of unified shared memory" section.

**Comment by imvucic** [comment]
Hi @gmlueck,

Thanks for clarification. We will proceed in next sprint with creating USM skeleton based on 3 sub-sections and merging  "Kinds of unified shared memory"  into "Basic concept" with smaller desc and link. The obstacles will be updated here and on the weekly.

**Comment by imvucic** [comment]
For constructors list should we following Table 99
[file:///home/mvucic/Downloads/spec-outputs/html/sycl-2020.html#table.constructors.usm-allocator](url)
```
  usm_allocator(const context& syclContext, const device& syclDevice,
              const property_list& propList = {});

  usm_allocator(const queue& syclQueue, const property_list& propList = {});
```

OR a synopsis of the usm_allocator class ?
```
usm_allocator(const context& syclContext,
                const device& syclDevice,
                const property_list& propList = {});
  usm_allocator(const queue& syclQueue,
                const property_list& propList = {});
  usm_allocator(const usm_allocator& other);
template <class U>
  usm_allocator(usm_allocator<U, AllocKind, Alignment> const&) noexcept;
```

**Comment by gmlueck** [comment]
I think it is sufficient to follow table 99.  The extra constructors in the synopsis are the standard ones that are common to all C++ allocators.  The vast majority of user applications will only use the ones in table 99.

**Comment by imvucic** [comment]
Ok, updated and following Table 99...One more notice:
Should we keep allocate, deallocate and operators ==, != explanation? I didn't founded construct and construct in rev8.

**Comment by gmlueck** [comment]
I think there is no need to describe these because they are part of the standard interface to a C++ allocator.  The most important part to describe are the two constructors in table 99 because those are specific to the SYCL USM allocator.  Users can find the description for the rest on cppreference.

It may be worthwhile to include a link to the cppreference description of the "Allocator" requirement: https://en.cppreference.com/w/cpp/named_req/Allocator

**Comment by imvucic** [comment]
All tasks from USM done and PRs merged. Closing issue.
